<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FutureSkillCoachLite.DomainService\FutureSkillCoachLite.DomainService.csproj" />
    <ProjectReference Include="..\FutureSkillCoachLite.Dto\FutureSkillCoachLite.Dto.csproj" />
    <ProjectReference Include="..\FutureSkillCoachLite.Exceptions\FutureSkillCoachLite.Exceptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Facades\" />
    <Folder Include="Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
