<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FutureSkillCoachLite.Infrastructure\FutureSkillCoachLite.Infrastructure.csproj" />
    <ProjectReference Include="..\FutureSkillCoachLite.Domain\FutureSkillCoachLite.Domain.csproj" />
    <ProjectReference Include="..\FutureSkillCoachLite.Dto\FutureSkillCoachLite.Dto.csproj" />
    <ProjectReference Include="..\FutureSkillCoachLite.Exceptions\FutureSkillCoachLite.Exceptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
